image:
  file: Dockerfile
ports:
  - port: 8000

tasks:
  - init: 'Initial configuration'
    command: |
    cp webvirtcloud/settings.py.template webvirtcloud/settings.py
    python3 -m venv venv
    . venv/bin/activate
    pip3 install -r conf/requirements.txt
    python3 manage.py migrate
